routes/admin_routes.py
from flask import Blueprint,render_template,redirect,url_for

bp_admin=Blueprint('admin',__name__,url_prefix='/admin/products')
#http://localhost:5000/admin/products
@bp_admin.route('/',methods=['GET'])
def index():
    return render_template('index.html')

#http://localhost:5000/admin/products/edit/13
@bp_admin.route('/edit/<int:id>',methods=['GET'])
def edit(id):
    if id<1:
        return redirect(url_for('index'))
    return render_template('update.html',id=id)

#http://localhost:5000/admin/products/create
@bp_admin.route('/create',methods=['GET'])
def create():
    return render_template('create.html')

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/styles.css">
    <title>Nuevo Producto</title>
</head>
<body >
<nav class="navbar navbar-expand-lg navbar-dark bg-dark my-3">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Productos
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{url_for('admin.create')}}">Nuevo</a></li>
            <li><a class="dropdown-item" href="{{url_for('admin.index')}}">Listar</a></li>

          </ul>
        </li>
       
      </ul>
    </div>
  </div>
</nav>
    <form action="http://localhost:5000/api/productos/add" method="post" enctype="multipart/form-data" 
    class="formularioAjax w-75 m-auto">
        <h1 class="text-center">Alta De Producto</h1>
        <div class="container bg-dark text-light rounded mb-3">
          <div class="row">
              <div class="col-12 mb-3">
                <label for="exampleFormControlInput1" class="form-label">Nombre</label>
                <input type="text" class="form-control" id="name" name="name">
                <span id="error-nombre" class="msjError"></span>
             </div>
             <div class="col-6 mb-3">
              <label for="exampleFormControlInput1" class="form-label">Precio</label>
              <input type="text" class="form-control" id="price" name="price">
              <span id="error-precio" class="msjError"></span>
            </div>

            <div class="col-6 mb-3">
              <label for="exampleFormControlInput1" class="form-label">Stock</label>
              <input type="number" class="form-control" id="stock" name="stock">
              <span id="error-stock" class="msjError"></span>
            </div>

            <div class="col-4 mb-3">
              <div>
                 <label for="category" class="form-label">Categorias</label>
              </div>
             
              <select name="category" id="category"></select>
              <span id="error-categoria" class="msjError"></span>
           </div>

           <div class="col-8 mb-3">
            <label for="img" class="form-label">Imagen</label>
            <input type="file" class="form-control" name='img' id="img">
            <span id="error-imagen" class="msjError"></span>
          </div>

          <div class="col-12 mb-3 ms-5">
            <div>
                 <label for="description" class="form-label">Descripcion</label>
                 
            </div>
           
            <textarea name="description" id="description" cols="100" rows="5"></textarea>
            <span id="error-descripcion" class="msjError"></span>
          </div>

           <div class=" col-12 d-flex justify-content-center mb-2">
            <div>
              <button type="submit" class="btn btn-primary">

              Enviar
            </button>
            </div>
            
          </div>
          </div>
        </div>
          
    </form>
</body>



<script src="/static/js/sweetalert/sweetalert.js"></script>
<script  type="module" src="/static/js/controlErrors.js"></script>
<script type="module" src="/static/js/createProducts.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="/static/css/styles.css">
  <title>Lista productos</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark my-3">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Productos
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{url_for('admin.create')}}">Nuevo</a></li>
            <li><a class="dropdown-item" href="{{url_for('admin.index')}}">Listar</a></li>

          </ul>
        </li>
       
      </ul>
    </div>
  </div>
 </nav>

 <div class="w-50 m-auto">
  <label for="filtroCategoria"> Categorias</label>
  <select class="form-select form-select-lg mb-3" name="filtroCategoria" id="filtroCategoria"
  aria-label=".form-select-lg example">
  <option value="0" selected >Todas</option>
  
</select>
 </div>
  <div
    class="table-responsive"
  >
    <table
      class="table table-striped table-hover table-borderless table-light"
    >
      <thead class="bg-primary">
        <caption>
          Productos
        </caption>
        <tr class="text-center">
          <th>Nombre</th>
          <th>Precio</th>
          <th>Stock</th>
          <th>Categoria</th>
          <th>Ver Detalles</th>
          <th>Actualizar</th>
          <th>Eliminar</th>
        </tr>
      </thead>
      <tbody class="table-group-divider text-center" id="tabla-productos">
        
      </tbody>
    </table>
  </div>
  
  
</body>
<script src="/static/js/sweetalert/sweetalert.js"></script>
<script src="/static/js/listProducts.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Actualizar</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark my-3">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Productos
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{url_for('admin.create')}}">Nuevo</a></li>
            <li><a class="dropdown-item" href="{{url_for('admin.index')}}">Listar</a></li>

          </ul>
        </li>
       
      </ul>
    </div>
  </div>
</nav>
   
    <form action="http://localhost:5000/api/productos/update" method="put" enctype="multipart/form-data" 
    class="formularioAjax w-75 m-auto">
        <h1 class="text-center">Actualizar Producto</h1>
        <div class="container bg-dark text-light rounded mb-3">
          <!--<input type="hidden" name="id" id="id" value="{{id}}">-->
          <div class="row">
              <div class="col-12 mb-3">
                <label for="exampleFormControlInput1" class="form-label">Nombre</label>
                <input type="text" class="form-control" id="name" name="name">
                <span id="error-nombre" class="msjError"></span>
             </div>
             <div class="col-6 mb-3">
              <label for="exampleFormControlInput1" class="form-label">Precio</label>
              <input type="text" class="form-control" id="price" name="price">
              <span id="error-precio" class="msjError"></span>
            </div>

            <div class="col-6 mb-3">
              <label for="exampleFormControlInput1" class="form-label">Stock</label>
              <input type="number" class="form-control" id="stock" name="stock">
              <span id="error-stock" class="msjError"></span>
            </div>

            <div class="col-4 mb-3">
              <div>
                 <label for="category" class="form-label">Categorias</label>
              </div>
             
              <select name="category" id="category"></select>
              <span id="error-categoria" class="msjError"></span>
           </div>

           <div class="col-8 mb-3">
            <label for="img" class="form-label">Imagen</label>
            <input type="file" class="form-control" name='img' id="img">
            <div>
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#imagenActual">
                    Ver Imagen Actual
              </button>
            </div>
            <span id="error-imagen" class="msjError"></span>
          </div>

          <div class="col-12 mb-3 ms-5">
            <div>
                 <label for="description" class="form-label">Descripcion</label>
                 
            </div>
           
            <textarea name="description" id="description" cols="100" rows="5"></textarea>
            <span id="error-descripcion" class="msjError"></span>
          </div>

           <div class=" col-12 d-flex justify-content-center mb-2">
            <div>
              <button type="submit" class="btn btn-primary">

              Enviar
            </button>
            </div>
            
          </div>
          </div>
        </div>
          
    </form>
</body>

<!-- Modal -->
<div class="modal fade" id="imagenActual" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Imagen Actual</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <img src="" alt="Imagen actual" id="imagenProductoActual">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

<script src="/static/js/sweetalert/sweetalert.js"></script>
<script type="module" src="/static/js/controlErrors.js"></script>
<script type="module" src="/static/js/updateProducts.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</html>